EXCEPTION: If a user is on the guides, the app needs to go back to the project, and change the link to the guides when the new project loads. That is why we watch for cwd and check if changed but is not the guides path, then we set `guidesIsActive` to false.